Fix exception in Firefox when iframes are deleted
A page can:

1. Hold a reference to elements in an iframe (if the origin is the same).
2. Remove the iframe from the page.
3. Add or remove event listeners to elements in the iframe.

This previously caused an exception in Firefox:

> TypeError: can't access dead object

This PR adds a workaround for this situation.

Fixes #99 (Proton Mail broken).

Supersedes #117. That PR tried to fix it by avoiding injections in
sandboxed iframes that don’t allow JavaScript, which fixes Proton Mail,
but does not fix the issue in general. The problem has nothing to to
with sandboxing, it’s just that Proton Mail happens to do that.